name: ????
description: ??????????????
title: "fix: "
labels: ["bug"]
body:
  - type: textarea
    id: current
    attributes:
      label: ????
      description: ????????
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: ????
      description: ????????????
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: ????
      description: ???????????????????
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: ????
      options:
        - S1 ??
        - S2 ??
        - S3 ??
        - S4 ??
    validations:
      required: true
