name: ????
description: ???????????????????????
title: "feat: "
labels: ["feature"]
body:
  - type: textarea
    id: background
    attributes:
      label: ?????
      description: ????????????????
    validations:
      required: true
  - type: dropdown
    id: module
    attributes:
      label: ??
      options:
        - ????
        - ????/????
        - ????
        - ????
        - ????
        - ????
        - ????
        - ????
        - ????
        - ????
        - ????
        - ????
        - ??/??/??
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: ???
      options:
        - P0
        - P1
        - P2
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: ????
      description: ??????????????
    validations:
      required: true
